FROM nvidia/cuda:12.4.0-runtime-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-pip git ffmpeg \
    libgl1 libsm6 libxext6 libglvnd-dev libxrender-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY req.txt .
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r req.txt

COPY ./src/ ./src/
COPY ./models/ ./models/
COPY server_upscale.py .

ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility
ENV FLASK_APP=server_upscale.py
ENV FLASK_ENV=production

EXPOSE 5001

CMD ["python3", "server_upscale.py"]
