FROM nvidia/cuda:12.4.0-runtime-ubuntu20.04 as builder

ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Etc/UTC \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-pip ffmpeg \
    # libgl1 libsm6 libxext6 libglvnd-dev libxrender-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install torch==2.1.1 torchvision==0.16.1 torchaudio==2.1.1 --index-url https://download.pytorch.org/whl/cu118 && \
    pip install --no-cache-dir -r requirements.txt
    
COPY ./src/ ./src/
COPY server_upscale.py .

ENV NVIDIA_VISIBLE_DEVICES=all \
    NVIDIA_DRIVER_CAPABILITIES=compute,utility \
    FLASK_APP=server_upscale.py \
    FLASK_ENV=production

EXPOSE 5001
CMD ["python3", "server_upscale.py"]
