FROM python:3.11-slim AS builder
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget gcc libffi-dev && \
    rm -rf /var/lib/apt/lists/*

FROM nvidia/cuda:12.4.0-runtime-ubuntu20.04 AS runtime

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

RUN apt-get update && apt-get install -y --no-install-recommends \
    git python3 python3-pip ffmpeg libgl1 libsm6 libxext6 libglvnd-dev libxrender-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*    

RUN apt-get update && apt-get install -y ffmpeg

COPY --from=builder /usr/local/lib/python3.11 /usr/local/lib/python3.11

WORKDIR /app

COPY ./req.txt .
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r req.txt

COPY /src/ .
COPY /models/ .

ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility
ENV FLASK_APP=server_upscale.py
ENV FLASK_ENV=production

EXPOSE 5001

CMD ["python3", "server_upscale.py"]
